apiVersion: v1
entries:
  agentic-web-research:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2026-07-01T12:09:33.725152221Z"
    description: Self-hosted web research service for AI agents
    digest: aea949287e404c4549399bdfe43e6d4842c93dffd6f6b41ee9a974ac48307128
    name: agentic-web-research
    type: application
    urls:
    - agentic-web-research-0.1.0.tgz
    version: 0.1.0
generated: "2026-07-01T12:09:33.724446734Z"
