apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentic-web-research.fullname" . }}
type: Opaque
stringData:
  APP_SECRET: {{ .Values.env.appSecret | quote }}
  ADMIN_PASSWORD: {{ .Values.env.adminPassword | quote }}
  DATABASE_URL: {{- if .Values.postgres.externalDatabaseUrl }} {{ .Values.postgres.externalDatabaseUrl | quote }}{{- else }} "postgres://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ include "agentic-web-research.fullname" . }}-postgres:5432/{{ .Values.postgres.database }}"{{- end }}

